theme: jekyll-theme-minimal
title: Kelly Shreeve's Data Science Portfolio
description: Data Scientist with a Master's Degree in Sociology and 5+ years' experience teaching statistics. After multiple years teaching, I felt the pull to build projects of my own. I'm enrolled in TripleTen's 10 month data science bootcamp and am currently learning Python and building Machine Learning projects. I will be applying to full time data science roles at the end of October 2023.
