theme: jekyll-theme-minimal
title: Kelly Shreeve
logo: /images/headshot_circle.png
description: >
  Data Scientist with M.A. in sociology, B.A. in environmental sociology, and 5+ years' experience 
  teaching statistics. Completed TripleTen's 10 month data science bootcamp and a
  real-world data science externship with DataSpeak. Currently accepting data analysis and statistics
  consulting projects May 2024.
  <br><br>
  <a href="https://www.linkedin.com/in/kelly-shreeve-statistics">View My LinkedIn Profile</a>
