theme: jekyll-theme-minimal
title: Kelly Shreeve
logo: /images/headshot_circle.png
description: >
  Data Scientist with a Master's Degree in Sociology and 5+ years' experience 
  teaching statistics. I'm enrolled in TripleTen's 10 month data science bootcamp
   and am currently learning Python and building Machine Learning projects. I will 
   be applying to full time data science roles at the end of October 2023.
  <br><br>
  <a href="www.linkedin.com/in/kelly-shreeve-statistics">View My LinkedIn Profile</a>